steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$REPO_NAME', '-t', 'gcr.io/granular-ai/$REPO_NAME:$SHORT_SHA', '-t', 'gcr.io/granular-ai/$REPO_NAME:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/granular-ai/$REPO_NAME:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/granular-ai/$REPO_NAME:$latest']