steps:
- name: 'Build Docker Image'
  args: ['build', '-t', '$REPO_NAME', '-t', 'gcr.io/granular-ai/$REPO_NAME:$SHORT_SHA', '-t', 'gcr.io/granular-ai/$REPO_NAME:latest', '.']
- name: 'Push'
  args: ['push', 'gcr.io/granular-ai/$REPO_NAME:$SHORT_SHA']