steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['./build.sh']
  env:
  - 'NAME=$REPO_NAME'
  - 'BRANCH=$BRANCH_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
logsBucket: 'gs://gcbblog'    